# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.ManyToManyField(to='web.TechnicalSkill'),
        ),
    ]
