# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_featured_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_stack_display',
            field=models.CharField(default='Python', max_length=75),
            preserve_default=False,
        ),
    ]
