# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-09 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170509_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_photo',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.s3_bucket_photo_upload),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_1',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.s3_bucket_photo_upload),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_2',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.s3_bucket_photo_upload),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_3',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.s3_bucket_photo_upload),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_4',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.s3_bucket_photo_upload),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_5',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.s3_bucket_photo_upload),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_6',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.s3_bucket_photo_upload),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_7',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.s3_bucket_photo_upload),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_8',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.s3_bucket_photo_upload),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_9',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.s3_bucket_photo_upload),
        ),
    ]
