stages:
  - test
  - deploy

test:
  type: test
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  # - export DATABASE_URL=postgres://postgres:@postgres:5432/atlas-api-db
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - python manage.py test

# This job is responsible for deploying the latest features in development to the development
# stage environment
stage dev deployment:
  type: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_DEV_APP --api-key=$HEROKU_API_KEY
  only:
  - stage-dev

# This job is responsible for patching the the release candidate environment in case a bug is
# found during RC testing
release candidate patch:
  type: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_STAGE_RC_APP --api-key=$HEROKU_API_KEY
  only:
  - stage-rc

# This job is responsible for patching the hotfix (production copy) environment
hotfix patch:
  type: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_HOTFIX_APP --api-key=$HEROKU_API_KEY
  only:
  - hotfix

# TODO: READ >> https://gitlab.com/help/ci/yaml/README.md#environment
