image: python:2.7
#services:
#  - postgres:9.5

before_script:
  - pip install --upgrade pip

stages:
  - build
  - test
  - deploy

#variables:
#  DATABASE_URL: "postgres://postgres@postgres/atlas"

test:
  type: test
#  before_script:
  script:
    - pip install -r requirements.txt
    - python manage.py test

stage deployment:
  type: deploy
  script:
#    - apt-get update -qy
#    - apt-get install -y ruby-dev
    - apt-get install rubygems
    - gem install dpl
    - dpl --provider=heroku --app=atlas11-stage --api-key=$HEROKU_API_KEY
  only:
  - master

#integration test:
#  type: test
#  script:
#    - python manage.py test

#test_job:
#  type: test
#  script:
    # - apt-get update -qy
    # - apt-get install -y python-dev python-pip
#    - pip install -r requirements.txt
#    - python manage.py test

# ===========================================================
# Everything below this line is what was here before
# ===========================================================

#test:
#  script:
#  # this configures Django application to use attached postgres database that is run on `postgres` host
#  # - export DATABASE_URL=postgres://postgres:@postgres:5432/atlas-api-db
#    - apt-get update -qy
#    - apt-get install -y python-dev python-pip
#    - pip install -r requirements.txt
#    - python manage.py test

#staging:
#  type: deploy
#  script:
#    - apt-get update -qy
#    - apt-get install -y ruby-dev
#    - gem install dpl
#    - dpl --provider=heroku --app=atlas11-stage --api-key=$HEROKU_API_KEY
#  only:
#  - master

#production:
#  type: deploy
#  script:
#  - apt-get update -qy
#  - apt-get install -y ruby-dev
#  - gem install dpl
#  - dpl --provider=heroku --app=gitlab-ci-python-test-prod --api-key=$HEROKU_PRODUCTION_API_KEY
#  only:
#  - tags

# TODO: READ >> https://gitlab.com/help/ci/yaml/README.md#environment
