stages:
  - test
  - deploy

test:
  type: test
  script:
  # - export DATABASE_URL=sqlite://atlas-api-db.sqlite3
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - python manage.py test -v 2

stage deployment:
  type: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_DEV_APP --api-key=$HEROKU_API_KEY
  only:
  - master

# This job is responsible for patching the hotfix (production copy) environment
hotfix patch:
  type: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_HOTFIX_APP --api-key=$HEROKU_API_KEY
  only:
  - hotfix

# TODO: READ >> https://gitlab.com/help/ci/yaml/README.md#environment
