#image: python:2.7
#services:
#  - postgres:9.5

stages:
  - test
  - deploy

test:
  type: test
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  # - export DATABASE_URL=postgres://postgres:@postgres:5432/atlas-api-db
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - python manage.py test

stage deployment:
  type: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_DEV_APPNAME --api-key=$HEROKU_API_KEY
  only:
  - master

hotfix deployment:
  type: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_PROD_COPY_APPNAME --api-key=$HEROKU_API_KEY
  only:
  - tags

# TODO: READ >> https://gitlab.com/help/ci/yaml/README.md#environment
