# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.7

pipelines:
  branches:
    master:
      - step:
          # set HEROKU_API_KEY and HEROKU_APP_NAME environment variables
          # set clone `depth: full' as described here: https://confluence.atlassian.com/x/Y9-5Mw
          name: Deploy to Production
          deployment: production   # set to test, staging or production
          # trigger: manual  # uncomment to have a manual step # TODO: For tagging maybe?
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
    develop:
      - step:
          # set HEROKU_API_KEY and HEROKU_APP_NAME environment variables
          # set clone `depth: full' as described here: https://confluence.atlassian.com/x/Y9-5Mw
          name: Deploy to Stage
          deployment: staging   # set to test, staging or production
          # trigger: manual  # uncomment to have a manual step
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
#    feature/*:
#    - step:
#        caches:
#          - pip
#        script: # Modify the commands below to build your repository. TODO: I need to add environment variables to get this to work
#          - pip install -r requirements.txt
#          - python manage.py test