version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: atlas_service
    volumes:
      - .:/atlas
    env_file: .env
    ports:
      - "8000:8000"