# Generated by Django 2.0.3 on 2018-09-29 19:41

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField()),
                ('location', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page')], default='home', max_length=6, unique=True)),
            ],
            options={
                'verbose_name_plural': 'about info',
                'db_table': 'about_info',
            },
        ),
        migrations.CreateModel(
            name='CareerSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('snapshot_type', models.CharField(choices=[('00', 'Academic'), ('01', 'Industry')], default='00', max_length=2)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'career_snapshot',
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('00', 'Frontend'), ('01', 'Backend'), ('02', 'DevOps'), ('03', 'Learning')], default='01', max_length=2)),
                ('font_awesome_icon', models.CharField(blank=True, max_length=90, null=True)),
                ('description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'expertise',
                'db_table': 'expertise',
            },
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('skill_type', models.CharField(choices=[('00', 'Framework'), ('01', 'Programming Language'), ('02', 'Data'), ('03', 'Deployment'), ('04', 'Development Tool')], default='00', max_length=2)),
                ('description', tinymce.models.HTMLField()),
            ],
            options={
                'db_table': 'technical_skill',
            },
        ),
    ]
