# Generated by Django 2.0.3 on 2018-10-02 18:53

import atlas.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinfo',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.web.models.s3_bucket_photo_upload),
        ),
    ]
