# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170103_1858'),
        ('web', '0002_expertise_technicalskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='technology_stack',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
