# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='technology_stack',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
