# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20170103_1959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CareerSnapshot',
            new_name='CareerPosition',
        ),
        migrations.AlterModelOptions(
            name='careerposition',
            options={},
        ),
        migrations.AlterModelTable(
            name='careerposition',
            table='career_position',
        ),
    ]
