# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20170103_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careersnapshot',
            old_name='title',
            new_name='company',
        ),
    ]
