# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_expertise_font_awesome_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalskill',
            name='skill_type',
            field=models.CharField(choices=[('00', 'Framework'), ('01', 'Programming Language'), ('02', 'Data'), ('03', 'Deployment'), ('03', 'Development Tool')], default='00', max_length=2),
        ),
    ]
