# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20170425_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechnologyStack',
        ),
    ]
