# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('industry', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('billing_street', models.CharField(blank=True, max_length=90, null=True)),
                ('billing_street_2', models.CharField(blank=True, max_length=30, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=90, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=2, null=True)),
                ('billing_zip', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountOwner'),
        ),
    ]
