# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page_description', tinymce.models.HTMLField()),
                ('about_page_description', tinymce.models.HTMLField()),
                ('personal_description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'about info',
            },
        ),
        migrations.CreateModel(
            name='CareerSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('snapshot_type', models.CharField(choices=[('00', 'Academic'), ('01', 'Industry')], default='00', max_length=2)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('experience_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('technology_type', models.CharField(choices=[('00', 'Framework'), ('01', 'Programming Language'), ('02', 'Other')], default='00', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='TechnologyStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('font_icon_class', models.CharField(max_length=25)),
                ('experience_description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AddField(
            model_name='technology',
            name='technology_stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TechnologyStack'),
        ),
    ]
