# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('00', 'Frontend'), ('01', 'Backend'), ('02', 'DevOps'), ('03', 'Learning')], default='01', max_length=2)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('skill_type', models.CharField(choices=[('00', 'Framework'), ('01', 'Programming Language'), ('02', 'Data'), ('03', 'Deployment')], default='00', max_length=2)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
    ]
