# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20170103_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careersnapshot',
            options={'verbose_name_plural': 'about info'},
        ),
        migrations.AlterModelOptions(
            name='expertise',
            options={'verbose_name_plural': 'expertise'},
        ),
        migrations.AlterModelOptions(
            name='technologystack',
            options={'verbose_name_plural': 'technology stack'},
        ),
        migrations.AlterModelTable(
            name='aboutinfo',
            table='about_info',
        ),
        migrations.AlterModelTable(
            name='careersnapshot',
            table='career_snapshot',
        ),
        migrations.AlterModelTable(
            name='expertise',
            table='expertise',
        ),
        migrations.AlterModelTable(
            name='technicalskill',
            table='technical_skill',
        ),
        migrations.AlterModelTable(
            name='technologystack',
            table='technology_stack',
        ),
    ]
