# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20170103_2015'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='careersnapshot',
            table='career_snapshot',
        ),
    ]
