# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20170424_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertise',
            name='font_awesome_icon',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
