# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        ('web', '0002_expertise_technicalskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('active_development', models.BooleanField(default=True)),
                ('project_completed', models.BooleanField(default=False)),
                ('display_on_website', models.BooleanField(default=True)),
                ('retired', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('main_photo', models.FileField(blank=True, null=True, upload_to='photos')),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('technology_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('release_instructions', tinymce.models.HTMLField(blank=True, null=True)),
                ('repo_url', models.URLField(blank=True, null=True)),
                ('stage_url', models.URLField(blank=True, null=True)),
                ('production_url', models.URLField(blank=True, null=True)),
                ('cloud_platform', models.CharField(blank=True, max_length=25, null=True)),
                ('cloud_platform_account', models.CharField(blank=True, max_length=50, null=True)),
                ('cloud_platform_console', models.URLField(blank=True, null=True)),
                ('domain_provider', models.CharField(blank=True, max_length=25, null=True)),
                ('domain_provider_account', models.CharField(blank=True, max_length=50, null=True)),
                ('domain_provider_console', models.URLField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('technology', models.ManyToManyField(to='web.Technology')),
            ],
        ),
    ]
