# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 17:42
from __future__ import unicode_literals

import atlas.projects.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('active_development', models.BooleanField(default=True)),
                ('project_completed', models.BooleanField(default=False)),
                ('display_on_website', models.BooleanField(default=True)),
                ('public_access', models.BooleanField(default=False)),
                ('featured_project', models.BooleanField(default=False)),
                ('retired', models.BooleanField(default=False)),
                ('tech_stack_display', models.CharField(blank=True, max_length=75, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload)),
                ('main_photo_thumb', models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload)),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload)),
                ('photo_1_thumb', models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload)),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload)),
                ('photo_2_thumb', models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload)),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload)),
                ('photo_3_thumb', models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload)),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload)),
                ('photo_4_thumb', models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload)),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload)),
                ('photo_5_thumb', models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload)),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload)),
                ('photo_6_thumb', models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload)),
                ('photo_7', models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload)),
                ('photo_7_thumb', models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload)),
                ('photo_8', models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload)),
                ('photo_8_thumb', models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload)),
                ('photo_9', models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload)),
                ('photo_9_thumb', models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('technology_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('release_instructions', tinymce.models.HTMLField(blank=True, null=True)),
                ('repo_url', models.URLField(blank=True, null=True)),
                ('stage_url', models.URLField(blank=True, null=True)),
                ('production_url', models.URLField(blank=True, null=True)),
                ('cloud_platform', models.CharField(blank=True, max_length=25, null=True)),
                ('cloud_platform_account', models.CharField(blank=True, max_length=50, null=True)),
                ('cloud_platform_console', models.URLField(blank=True, null=True)),
                ('domain_provider', models.CharField(blank=True, max_length=25, null=True)),
                ('domain_provider_account', models.CharField(blank=True, max_length=50, null=True)),
                ('domain_provider_console', models.URLField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('technology', models.ManyToManyField(to='web.TechnicalSkill')),
            ],
        ),
    ]
