# Generated by Django 2.0.3 on 2018-10-02 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='public_access',
            new_name='public_repo',
        ),
    ]
