# Generated by Django 2.0.3 on 2018-10-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181002_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphoto',
            name='main_photo',
            field=models.BooleanField(default=False),
        ),
    ]
