# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170103_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_project',
            field=models.BooleanField(default=False),
        ),
    ]
