# Generated by Django 2.0.3 on 2018-10-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20181002_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectphoto',
            old_name='photo',
            new_name='url',
        ),
    ]
