# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-09 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_tech_stack_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo_1',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_2',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_3',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_4',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_5',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_6',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_7',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_8',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_9',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack_display',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
