# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-10 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20170509_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_photo_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_1_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_2_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_3_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_4_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_5_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_6_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_7_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_8_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_9_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_7',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_8',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_9',
            field=models.ImageField(blank=True, null=True, upload_to=atlas.projects.models.s3_bucket_photo_upload),
        ),
    ]
